### ISSUE TITLE
[Feature]: Lower number of ahorn/loenn(?) plugins

### ISSUE THREAD

**Issue by ABuffZucchini** [CommunalHelper/OutbackHelper#2]
### Request Description

Hi so basically I was wondering if it would be possible to change the Portal (Direction, Color) format to just Portal (Direction) because now that there are 16 different portal colors across 5 different directions, there are 80 plugins for almost identical entities, which I feel is a little bit unnecessary and clutters an already very overfilled interface. My idea is to simply make one plugin for each direction, since you can already change the color in the entity settings.
![image](https://user-images.githubusercontent.com/55515577/223804399-1da00298-4456-45d9-b948-cc0bbd58ec3c.png)

**Comment by bigkahuna443** [comment]
Fixed in 1.7.2, thanks for reporting!
