### ISSUE TITLE
[Bug]: Ahorn Plugins Missing Graphic

### ISSUE THREAD

**Issue by ABuffZucchini** [CommunalHelper/OutbackHelper#4]
### Before You Report

- [X] My mods and Everest install are up to date.
- [X] I have recreated the bug with a minimum number of mods installed.

### What platform are you playing on?

Windows 10 FNA

### Bug Description

So basically, a couple of the new portal sprites are missing in ahorn (at least im pretty sure that's what this is), which leads to ahorn freezing up if you try to select them. This effectively makes the Olive color portal currently unusable for ahorn users.

### Steps to Reproduce

Simply set a portal to the color Olive and ahorn will scream and cry until you undo it.

**Comment by bigkahuna443** [comment]
Fixed in #1
